// Please use the following editor setup for this file:
// Tab size=2; Tabs as spaces; Clean up trailing whitepsace
//
// In vim add: au FileType proto setl sw=2 ts=2 expandtab list
//
// In vscode install vscode-proto3 extension and add this to your settings.json:
//    "[proto3]": {
//        "editor.tabSize": 2,
//        "editor.insertSpaces": true,
//        "editor.rulers": [80],
//        "editor.detectIndentation": true,
//        "files.trimTrailingWhitespace": true
//    }
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: api/rpcscout.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// These values are constants that can be used by the
// client and server applications
type ScoutVersion_Version int32

const (
	// Must be set in the proto file; ignore.
	ScoutVersion_MUST_HAVE_ZERO_VALUE ScoutVersion_Version = 0
	// Version major value of this specification
	ScoutVersion_MAJOR ScoutVersion_Version = 0
	// Version minor value of this specification
	ScoutVersion_MINOR ScoutVersion_Version = 0
	// Version patch value of this specification
	ScoutVersion_PATCH ScoutVersion_Version = 1
)

// Enum value maps for ScoutVersion_Version.
var (
	ScoutVersion_Version_name = map[int32]string{
		0: "MUST_HAVE_ZERO_VALUE",
		// Duplicate value: 0: "MAJOR",
		// Duplicate value: 0: "MINOR",
		1: "PATCH",
	}
	ScoutVersion_Version_value = map[string]int32{
		"MUST_HAVE_ZERO_VALUE": 0,
		"MAJOR":                0,
		"MINOR":                0,
		"PATCH":                1,
	}
)

func (x ScoutVersion_Version) Enum() *ScoutVersion_Version {
	p := new(ScoutVersion_Version)
	*p = x
	return p
}

func (x ScoutVersion_Version) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScoutVersion_Version) Descriptor() protoreflect.EnumDescriptor {
	return file_api_rpcscout_proto_enumTypes[0].Descriptor()
}

func (ScoutVersion_Version) Type() protoreflect.EnumType {
	return &file_api_rpcscout_proto_enumTypes[0]
}

func (x ScoutVersion_Version) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScoutVersion_Version.Descriptor instead.
func (ScoutVersion_Version) EnumDescriptor() ([]byte, []int) {
	return file_api_rpcscout_proto_rawDescGZIP(), []int{12, 0}
}

// Used to track information from the client in the logs
type ClientInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Set by the client to be used by the server on response
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the client
	ClientName string `protobuf:"bytes,2,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	// Timestamp when the request was sent
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rpcscout_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpcscout_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_api_rpcscout_proto_rawDescGZIP(), []int{0}
}

func (x *ClientInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClientInfo) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *ClientInfo) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ServerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// client id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// server name
	ServerName string `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	// Timestamp when the server replied
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rpcscout_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpcscout_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_api_rpcscout_proto_rawDescGZIP(), []int{1}
}

func (x *ServerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServerInfo) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ServerInfo) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Empty request
type ScoutListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Information about the requester
	Client *ClientInfo `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
}

func (x *ScoutListRequest) Reset() {
	*x = ScoutListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rpcscout_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoutListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoutListRequest) ProtoMessage() {}

func (x *ScoutListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpcscout_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoutListRequest.ProtoReflect.Descriptor instead.
func (*ScoutListRequest) Descriptor() ([]byte, []int) {
	return file_api_rpcscout_proto_rawDescGZIP(), []int{2}
}

func (x *ScoutListRequest) GetClient() *ClientInfo {
	if x != nil {
		return x.Client
	}
	return nil
}

type ScoutListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Server information
	Server *ServerInfo `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	// List of stuff
	List []string `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ScoutListResponse) Reset() {
	*x = ScoutListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rpcscout_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoutListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoutListResponse) ProtoMessage() {}

func (x *ScoutListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpcscout_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoutListResponse.ProtoReflect.Descriptor instead.
func (*ScoutListResponse) Descriptor() ([]byte, []int) {
	return file_api_rpcscout_proto_rawDescGZIP(), []int{3}
}

func (x *ScoutListResponse) GetServer() *ServerInfo {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *ScoutListResponse) GetList() []string {
	if x != nil {
		return x.List
	}
	return nil
}

type ScoutDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Information about the requester
	Client *ClientInfo `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	// Fake id to delete
	DeleteId string `protobuf:"bytes,2,opt,name=delete_id,json=deleteId,proto3" json:"delete_id,omitempty"`
}

func (x *ScoutDeleteRequest) Reset() {
	*x = ScoutDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rpcscout_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoutDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoutDeleteRequest) ProtoMessage() {}

func (x *ScoutDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpcscout_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoutDeleteRequest.ProtoReflect.Descriptor instead.
func (*ScoutDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_rpcscout_proto_rawDescGZIP(), []int{4}
}

func (x *ScoutDeleteRequest) GetClient() *ClientInfo {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *ScoutDeleteRequest) GetDeleteId() string {
	if x != nil {
		return x.DeleteId
	}
	return ""
}

// Empty response
type ScoutDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Server information
	Server *ServerInfo `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
}

func (x *ScoutDeleteResponse) Reset() {
	*x = ScoutDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rpcscout_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoutDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoutDeleteResponse) ProtoMessage() {}

func (x *ScoutDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpcscout_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoutDeleteResponse.ProtoReflect.Descriptor instead.
func (*ScoutDeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_rpcscout_proto_rawDescGZIP(), []int{5}
}

func (x *ScoutDeleteResponse) GetServer() *ServerInfo {
	if x != nil {
		return x.Server
	}
	return nil
}

type ScoutStreamDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Client *ClientInfo `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
}

func (x *ScoutStreamDataRequest) Reset() {
	*x = ScoutStreamDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rpcscout_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoutStreamDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoutStreamDataRequest) ProtoMessage() {}

func (x *ScoutStreamDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpcscout_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoutStreamDataRequest.ProtoReflect.Descriptor instead.
func (*ScoutStreamDataRequest) Descriptor() ([]byte, []int) {
	return file_api_rpcscout_proto_rawDescGZIP(), []int{6}
}

func (x *ScoutStreamDataRequest) GetClient() *ClientInfo {
	if x != nil {
		return x.Client
	}
	return nil
}

type ScoutStreamDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Server information
	Server *ServerInfo `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	// Random data
	RandomNumber int32 `protobuf:"varint,2,opt,name=random_number,json=randomNumber,proto3" json:"random_number,omitempty"`
}

func (x *ScoutStreamDataResponse) Reset() {
	*x = ScoutStreamDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rpcscout_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoutStreamDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoutStreamDataResponse) ProtoMessage() {}

func (x *ScoutStreamDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpcscout_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoutStreamDataResponse.ProtoReflect.Descriptor instead.
func (*ScoutStreamDataResponse) Descriptor() ([]byte, []int) {
	return file_api_rpcscout_proto_rawDescGZIP(), []int{7}
}

func (x *ScoutStreamDataResponse) GetServer() *ServerInfo {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *ScoutStreamDataResponse) GetRandomNumber() int32 {
	if x != nil {
		return x.RandomNumber
	}
	return 0
}

type ScoutPingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Client *ClientInfo `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
}

func (x *ScoutPingRequest) Reset() {
	*x = ScoutPingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rpcscout_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoutPingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoutPingRequest) ProtoMessage() {}

func (x *ScoutPingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpcscout_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoutPingRequest.ProtoReflect.Descriptor instead.
func (*ScoutPingRequest) Descriptor() ([]byte, []int) {
	return file_api_rpcscout_proto_rawDescGZIP(), []int{8}
}

func (x *ScoutPingRequest) GetClient() *ClientInfo {
	if x != nil {
		return x.Client
	}
	return nil
}

type ScoutPingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Server information
	Server *ServerInfo `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
}

func (x *ScoutPingResponse) Reset() {
	*x = ScoutPingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rpcscout_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoutPingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoutPingResponse) ProtoMessage() {}

func (x *ScoutPingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpcscout_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoutPingResponse.ProtoReflect.Descriptor instead.
func (*ScoutPingResponse) Descriptor() ([]byte, []int) {
	return file_api_rpcscout_proto_rawDescGZIP(), []int{9}
}

func (x *ScoutPingResponse) GetServer() *ServerInfo {
	if x != nil {
		return x.Server
	}
	return nil
}

// Empty request
type ScoutIdentityVersionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScoutIdentityVersionRequest) Reset() {
	*x = ScoutIdentityVersionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rpcscout_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoutIdentityVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoutIdentityVersionRequest) ProtoMessage() {}

func (x *ScoutIdentityVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpcscout_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoutIdentityVersionRequest.ProtoReflect.Descriptor instead.
func (*ScoutIdentityVersionRequest) Descriptor() ([]byte, []int) {
	return file_api_rpcscout_proto_rawDescGZIP(), []int{10}
}

// Defines the response to version
type ScoutIdentityVersionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Scout application version
	ScoutVersion *ScoutVersion `protobuf:"bytes,1,opt,name=Scout_version,json=ScoutVersion,proto3" json:"Scout_version,omitempty"`
}

func (x *ScoutIdentityVersionResponse) Reset() {
	*x = ScoutIdentityVersionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rpcscout_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoutIdentityVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoutIdentityVersionResponse) ProtoMessage() {}

func (x *ScoutIdentityVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpcscout_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoutIdentityVersionResponse.ProtoReflect.Descriptor instead.
func (*ScoutIdentityVersionResponse) Descriptor() ([]byte, []int) {
	return file_api_rpcscout_proto_rawDescGZIP(), []int{11}
}

func (x *ScoutIdentityVersionResponse) GetScoutVersion() *ScoutVersion {
	if x != nil {
		return x.ScoutVersion
	}
	return nil
}

// Scout version in Major.Minor.Patch format. The goal of this
// message is to provide clients a method to determine the server
// and client versions.
type ScoutVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Version major number
	Major int32 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	// Version minor number
	Minor int32 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	// Version patch number
	Patch int32 `protobuf:"varint,3,opt,name=patch,proto3" json:"patch,omitempty"`
	// String representation of the version. Must be
	// in `major.minor.patch` format.
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *ScoutVersion) Reset() {
	*x = ScoutVersion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rpcscout_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoutVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoutVersion) ProtoMessage() {}

func (x *ScoutVersion) ProtoReflect() protoreflect.Message {
	mi := &file_api_rpcscout_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoutVersion.ProtoReflect.Descriptor instead.
func (*ScoutVersion) Descriptor() ([]byte, []int) {
	return file_api_rpcscout_proto_rawDescGZIP(), []int{12}
}

func (x *ScoutVersion) GetMajor() int32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *ScoutVersion) GetMinor() int32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *ScoutVersion) GetPatch() int32 {
	if x != nil {
		return x.Patch
	}
	return 0
}

func (x *ScoutVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_api_rpcscout_proto protoreflect.FileDescriptor

var file_api_rpcscout_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x70, 0x63, 0x73, 0x63, 0x6f, 0x75, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x70, 0x63, 0x73, 0x63, 0x6f, 0x75, 0x74, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x77, 0x0a,
	0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x77, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22,
	0x40, 0x0a, 0x10, 0x53, 0x63, 0x6f, 0x75, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x72, 0x70, 0x63, 0x73, 0x63, 0x6f, 0x75, 0x74, 0x2e, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x22, 0x55, 0x0a, 0x11, 0x53, 0x63, 0x6f, 0x75, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x72, 0x70, 0x63, 0x73, 0x63, 0x6f, 0x75,
	0x74, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x5f, 0x0a, 0x12, 0x53, 0x63, 0x6f, 0x75,
	0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c,
	0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x72, 0x70, 0x63, 0x73, 0x63, 0x6f, 0x75, 0x74, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x64, 0x22, 0x43, 0x0a, 0x13, 0x53, 0x63, 0x6f,
	0x75, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2c, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x72, 0x70, 0x63, 0x73, 0x63, 0x6f, 0x75, 0x74, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x46,
	0x0a, 0x16, 0x53, 0x63, 0x6f, 0x75, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x72, 0x70, 0x63, 0x73, 0x63,
	0x6f, 0x75, 0x74, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x6c, 0x0a, 0x17, 0x53, 0x63, 0x6f, 0x75, 0x74, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x72, 0x70, 0x63, 0x73, 0x63, 0x6f, 0x75, 0x74, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12,
	0x23, 0x0a, 0x0d, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x22, 0x40, 0x0a, 0x10, 0x53, 0x63, 0x6f, 0x75, 0x74, 0x50, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x72, 0x70, 0x63, 0x73, 0x63,
	0x6f, 0x75, 0x74, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x41, 0x0a, 0x11, 0x53, 0x63, 0x6f, 0x75, 0x74, 0x50,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x72, 0x70,
	0x63, 0x73, 0x63, 0x6f, 0x75, 0x74, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x1d, 0x0a, 0x1b, 0x53, 0x63, 0x6f,
	0x75, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5b, 0x0a, 0x1c, 0x53, 0x63, 0x6f, 0x75,
	0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0d, 0x53, 0x63, 0x6f, 0x75,
	0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x72, 0x70, 0x63, 0x73, 0x63, 0x6f, 0x75, 0x74, 0x2e, 0x53, 0x63, 0x6f, 0x75, 0x74,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x53, 0x63, 0x6f, 0x75, 0x74, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xb4, 0x01, 0x0a, 0x0c, 0x53, 0x63, 0x6f, 0x75, 0x74, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x69, 0x6e,
	0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x74, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x70, 0x61, 0x74, 0x63, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x48, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a,
	0x14, 0x4d, 0x55, 0x53, 0x54, 0x5f, 0x48, 0x41, 0x56, 0x45, 0x5f, 0x5a, 0x45, 0x52, 0x4f, 0x5f,
	0x56, 0x41, 0x4c, 0x55, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x41, 0x4a, 0x4f, 0x52,
	0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x49, 0x4e, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x09, 0x0a,
	0x05, 0x50, 0x41, 0x54, 0x43, 0x48, 0x10, 0x01, 0x1a, 0x02, 0x10, 0x01, 0x32, 0x81, 0x03, 0x0a,
	0x05, 0x53, 0x63, 0x6f, 0x75, 0x74, 0x12, 0x5f, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x1a,
	0x2e, 0x72, 0x70, 0x63, 0x73, 0x63, 0x6f, 0x75, 0x74, 0x2e, 0x53, 0x63, 0x6f, 0x75, 0x74, 0x50,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x72, 0x70, 0x63,
	0x73, 0x63, 0x6f, 0x75, 0x74, 0x2e, 0x53, 0x63, 0x6f, 0x75, 0x74, 0x50, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x22,
	0x13, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x73, 0x63, 0x6f, 0x75, 0x74, 0x2f, 0x76, 0x31, 0x2f,
	0x70, 0x69, 0x6e, 0x67, 0x3a, 0x01, 0x2a, 0x12, 0x5c, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x1a, 0x2e, 0x72, 0x70, 0x63, 0x73, 0x63, 0x6f, 0x75, 0x74, 0x2e, 0x53, 0x63, 0x6f, 0x75, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x72, 0x70,
	0x63, 0x73, 0x63, 0x6f, 0x75, 0x74, 0x2e, 0x53, 0x63, 0x6f, 0x75, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15,
	0x12, 0x13, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x73, 0x63, 0x6f, 0x75, 0x74, 0x2f, 0x76, 0x31,
	0x2f, 0x64, 0x61, 0x74, 0x61, 0x12, 0x62, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x1c, 0x2e, 0x72, 0x70, 0x63, 0x73, 0x63, 0x6f, 0x75, 0x74, 0x2e, 0x53, 0x63, 0x6f, 0x75, 0x74,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x72, 0x70, 0x63, 0x73, 0x63, 0x6f, 0x75, 0x74, 0x2e, 0x53, 0x63, 0x6f, 0x75, 0x74, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x15, 0x2a, 0x13, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x73, 0x63, 0x6f, 0x75,
	0x74, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x12, 0x55, 0x0a, 0x0a, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x12, 0x20, 0x2e, 0x72, 0x70, 0x63, 0x73, 0x63, 0x6f,
	0x75, 0x74, 0x2e, 0x53, 0x63, 0x6f, 0x75, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x72, 0x70, 0x63, 0x73,
	0x63, 0x6f, 0x75, 0x74, 0x2e, 0x53, 0x63, 0x6f, 0x75, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01,
	0x32, 0x87, 0x01, 0x0a, 0x0d, 0x53, 0x63, 0x6f, 0x75, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x12, 0x76, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x2e,
	0x72, 0x70, 0x63, 0x73, 0x63, 0x6f, 0x75, 0x74, 0x2e, 0x53, 0x63, 0x6f, 0x75, 0x74, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x72, 0x70, 0x63, 0x73, 0x63, 0x6f, 0x75, 0x74, 0x2e,
	0x53, 0x63, 0x6f, 0x75, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1c, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x16, 0x12, 0x14, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x2f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x1c, 0x0a, 0x0d, 0x63, 0x6f,
	0x6d, 0x2e, 0x53, 0x63, 0x6f, 0x75, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x50, 0x01, 0x5a, 0x09, 0x2e,
	0x2f, 0x61, 0x70, 0x69, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_rpcscout_proto_rawDescOnce sync.Once
	file_api_rpcscout_proto_rawDescData = file_api_rpcscout_proto_rawDesc
)

func file_api_rpcscout_proto_rawDescGZIP() []byte {
	file_api_rpcscout_proto_rawDescOnce.Do(func() {
		file_api_rpcscout_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_rpcscout_proto_rawDescData)
	})
	return file_api_rpcscout_proto_rawDescData
}

var file_api_rpcscout_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_rpcscout_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_rpcscout_proto_goTypes = []interface{}{
	(ScoutVersion_Version)(0),            // 0: rpcscout.ScoutVersion.Version
	(*ClientInfo)(nil),                   // 1: rpcscout.ClientInfo
	(*ServerInfo)(nil),                   // 2: rpcscout.ServerInfo
	(*ScoutListRequest)(nil),             // 3: rpcscout.ScoutListRequest
	(*ScoutListResponse)(nil),            // 4: rpcscout.ScoutListResponse
	(*ScoutDeleteRequest)(nil),           // 5: rpcscout.ScoutDeleteRequest
	(*ScoutDeleteResponse)(nil),          // 6: rpcscout.ScoutDeleteResponse
	(*ScoutStreamDataRequest)(nil),       // 7: rpcscout.ScoutStreamDataRequest
	(*ScoutStreamDataResponse)(nil),      // 8: rpcscout.ScoutStreamDataResponse
	(*ScoutPingRequest)(nil),             // 9: rpcscout.ScoutPingRequest
	(*ScoutPingResponse)(nil),            // 10: rpcscout.ScoutPingResponse
	(*ScoutIdentityVersionRequest)(nil),  // 11: rpcscout.ScoutIdentityVersionRequest
	(*ScoutIdentityVersionResponse)(nil), // 12: rpcscout.ScoutIdentityVersionResponse
	(*ScoutVersion)(nil),                 // 13: rpcscout.ScoutVersion
	(*timestamppb.Timestamp)(nil),        // 14: google.protobuf.Timestamp
}
var file_api_rpcscout_proto_depIdxs = []int32{
	14, // 0: rpcscout.ClientInfo.timestamp:type_name -> google.protobuf.Timestamp
	14, // 1: rpcscout.ServerInfo.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 2: rpcscout.ScoutListRequest.client:type_name -> rpcscout.ClientInfo
	2,  // 3: rpcscout.ScoutListResponse.server:type_name -> rpcscout.ServerInfo
	1,  // 4: rpcscout.ScoutDeleteRequest.client:type_name -> rpcscout.ClientInfo
	2,  // 5: rpcscout.ScoutDeleteResponse.server:type_name -> rpcscout.ServerInfo
	1,  // 6: rpcscout.ScoutStreamDataRequest.client:type_name -> rpcscout.ClientInfo
	2,  // 7: rpcscout.ScoutStreamDataResponse.server:type_name -> rpcscout.ServerInfo
	1,  // 8: rpcscout.ScoutPingRequest.client:type_name -> rpcscout.ClientInfo
	2,  // 9: rpcscout.ScoutPingResponse.server:type_name -> rpcscout.ServerInfo
	13, // 10: rpcscout.ScoutIdentityVersionResponse.Scout_version:type_name -> rpcscout.ScoutVersion
	9,  // 11: rpcscout.Scout.Ping:input_type -> rpcscout.ScoutPingRequest
	3,  // 12: rpcscout.Scout.List:input_type -> rpcscout.ScoutListRequest
	5,  // 13: rpcscout.Scout.Delete:input_type -> rpcscout.ScoutDeleteRequest
	7,  // 14: rpcscout.Scout.StreamData:input_type -> rpcscout.ScoutStreamDataRequest
	11, // 15: rpcscout.ScoutIdentity.Version:input_type -> rpcscout.ScoutIdentityVersionRequest
	10, // 16: rpcscout.Scout.Ping:output_type -> rpcscout.ScoutPingResponse
	4,  // 17: rpcscout.Scout.List:output_type -> rpcscout.ScoutListResponse
	6,  // 18: rpcscout.Scout.Delete:output_type -> rpcscout.ScoutDeleteResponse
	8,  // 19: rpcscout.Scout.StreamData:output_type -> rpcscout.ScoutStreamDataResponse
	12, // 20: rpcscout.ScoutIdentity.Version:output_type -> rpcscout.ScoutIdentityVersionResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_rpcscout_proto_init() }
func file_api_rpcscout_proto_init() {
	if File_api_rpcscout_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_rpcscout_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rpcscout_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rpcscout_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoutListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rpcscout_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoutListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rpcscout_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoutDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rpcscout_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoutDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rpcscout_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoutStreamDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rpcscout_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoutStreamDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rpcscout_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoutPingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rpcscout_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoutPingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rpcscout_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoutIdentityVersionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rpcscout_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoutIdentityVersionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rpcscout_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoutVersion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_rpcscout_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_rpcscout_proto_goTypes,
		DependencyIndexes: file_api_rpcscout_proto_depIdxs,
		EnumInfos:         file_api_rpcscout_proto_enumTypes,
		MessageInfos:      file_api_rpcscout_proto_msgTypes,
	}.Build()
	File_api_rpcscout_proto = out.File
	file_api_rpcscout_proto_rawDesc = nil
	file_api_rpcscout_proto_goTypes = nil
	file_api_rpcscout_proto_depIdxs = nil
}
